### PR TITLE
some fixes and refactoring

### PR DESCRIPTION
**Pull request by mindw**
- fix 2.x regressions
- use setuptools
- use setuptools-scm

### CODE REVIEW

**Comment by jswhit** [comment]
Thanks - did you also contribute this upstream (https://github.com/BurntSushi/pdoc)?  I've opened an issue there with my cython fixes (https://github.com/BurntSushi/pdoc/issues/49), but so far the developer has not responded - that's why I continue to maintain this fork.

**Comment by mindw** [comment]
And that's why I made the pull request here.

Thanks!

**Comment by jswhit** [comment]
I'll go ahead and make a pull request at https://github.com/BurntSushi/pdoc, with all the changes so far in this fork.

**Comment by mindw** [comment]
Be my guest :)

-gabi

**Comment by jswhit** [comment]
https://github.com/BurntSushi/pdoc/pull/68

**Pull request merged**
